name: superheroes
description: A simple app showing a list of superheroes.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Shared preferences
  shared_preferences: ^2.3.3
  # Dependency Injection (DI)
  get_it: ^8.0.2
  # Navigation
  go_router: ^14.6.2
  # Assets / UI
  cached_network_image: ^3.4.1
  material_symbols_icons: ^4.2789.0
  lottie: ^3.2.0
  vector_graphics: any
  google_fonts: ^6.2.1
  # HTTP
  http: ^1.2.2
  # Translation
  flutter_localizations:
    sdk: flutter
  intl: any
  intl_utils: ^2.8.7
  # Env keys
  flutter_dotenv: ^5.2.1
  

dev_dependencies:
  # Tests
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  flutter_lints: ^2.0.0

  build_runner: ^2.4.8
  flutter_gen_runner: ^5.8.0

flutter_gen:
  output: lib/core/commons/ui/assets/
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/images/
    - assets/lottie/

flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: lib/core/commons/services/translation/l10n
  output_dir: lib/core/commons/services/translation/generated